spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/learningenglish
spring.datasource.username=root
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.security.oauth2.resourceserver.jwt.secret=12576576587689778901222222222222
logging.level.root=DEBUG

logging.level.com.th=DEBUG

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

logging.level.org.springframework.security=DEBUG


# MoMo payment config
momo.partnerCode=MOMO
momo.accessKey=F8BBA842ECF85
momo.secretKey=K951B6PE1waDMi640xX08PD3vg6EkVlz
momo.endpoint=https://test-payment.momo.vn/v2/gateway/api/create
momo.ipnUrl=https://new-sadly-shepherd.ngrok-free.app/api/payments/confirm/momo-ipn

momo.redirectUrl=http://localhost:8080/api/payments/momo/return

ngrok http --url=new-sadly-shepherd.ngrok-free.app 8080

gemini.api.key=AIzaSyBIcso7YQQcs_kPcdO4adMyAODxlRqr-nM
